# Generated by Django 2.2 on 2019-04-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('que', models.IntegerField(default=0)),
            ],
        ),
    ]
