# Generated by Django 2.2 on 2019-05-23 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190512_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brstate',
            name='notifier',
            field=models.CharField(default=[{}], max_length=1000),
        ),
    ]
