# Generated by Django 2.2 on 2019-10-04 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190523_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brstate',
            name='notifier',
        ),
    ]
