# Generated by Django 2.2 on 2019-10-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_brstate_notifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='brstate',
            name='notifier',
            field=models.CharField(default=[{}], max_length=1000),
        ),
    ]
